name: Pull Request To Main
run-name: Run All Tests
on:
  pull_request:
    branches:
      - 'main'
jobs:
  unit_testing:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Unit Tests
        run: |
          chmod +x ./test/unit-tests.sh
          ./test/unit-tests.sh
        
  integration_testing:
    runs-on: self-hosted
    container: python:3.12.3-slim
    services:
      db:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: 123
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
  mega_hard_testing:
    needs: [unit_testing, integration_testing]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Mega Hard Tests
        run: |
          chmod +x ./test/all-mega-hard-tests.sh
          ./test/all-mega-hard-tests.sh
